### ISSUE TITLE
[Raspberry Pi] Module broken since 3.18 kernel mainline

### ISSUE THREAD

**Issue by argos66** [gkaindl/rfm12b-linux#11]
Module doesn't work with the last raspberry-pi kernel mainline (rpi-3.18.y).
insmod work after configured device-tree to add spi-bcm2708 but not work to achieve packet reception in exemple programm, work good on old rpi-3.12.y branch.

EDIT: exact version 3.18.7

**Comment by gkaindl** [comment]
hm, not sure, I just pushed some updates, so please try again?

I've tested the current master on Raspbian's 3.18.11-v7 kernel, works fine there.
