### ISSUE TITLE
Insmod error

### ISSUE THREAD

**Issue by klattimer** [gkaindl/rfm12b-linux#12]
When running insmod rfm12b.ko

I get the following error including a segmentation fault

[   36.909874] Internal error: Oops: 5 [#1] PREEMPT SMP ARM
[   36.930848] Modules linked in: rfm12b(O+) snd_soc_pcm512x_i2c snd_soc_pcm512x snd_soc_wm8804 snd_soc_tas5713 regmap_spi snd_soc_bcm2708_i2s regmap_mmio regmap_i2c snd_soc_core snd_compress snd_pcm_dmaengine snd_pcm snd_timer snd i2c_bcm2708 spi_bcm2708
[   37.015737] CPU: 2 PID: 284 Comm: insmod Tainted: G        W  O   3.18.0-trunk-rpi2 #1 Debian 3.18.5-1~exp1.co1
[   37.056599] task: b4035200 ti: b775a000 task.ti: b775a000
[   37.077148] PC is at rfm12_init_module+0x64/0x214 [rfm12b]
[   37.097559] LR is at rfm12_init_module+0x60/0x214 [rfm12b]
[   37.117363] pc : [<7f0cb064>]    lr : [<7f0cb060>]    psr: 800f0013
sp : b775bda8  ip : 0000000d  fp : b775bdd4
[   37.156882] r10: 00000000  r9 : 00000000  r8 : 00000000
[   37.175557] r7 : 00000007  r6 : 00000004  r5 : 7f0c8fe0  r4 : 00000008
[   37.195124] r3 : 00000000  r2 : 0000000a  r1 : 00000007  r0 : 00000000
[   37.214187] Flags: Nzcv  IRQs on  FIQs on  Mode SVC_32  ISA ARM  Segment user
[   37.233805] Control: 10c5387d  Table: 3927006a  DAC: 00000015
[   37.251918] Process insmod (pid: 284, stack limit = 0xb775a238)
[   37.269995] Stack: (0xb775bda8 to 0xb775c000)
[   37.286262] bda0:                   80161c90 800f1074 b775a018 809a9d4c 809ade18 b7626988
[   37.318155] bdc0: 809ade18 b9152700 b775be64 b775bdd8 80008950 7f0cb00c 80152138 00000009
[   37.350275] bde0: 8098bad0 7f0cb000 a0070013 396f3000 ba07ead0 7f0c8e48 b775be2c b775be08
[   37.383655] be00: 80161c90 800f1074 00000002 00000009 b9152700 bbd37000 00000001 00000001
[   37.417939] be20: b775be4c b775be30 80153c9c 80161c00 b775bf48 dc8cb005 b7626980 b775bf48
[   37.452136] be40: 00000001 b7626980 b7626988 00000001 7f0c8e48 7f0c8e54 b775bf3c b775be68
[   37.486655] be60: 800a70f0 80008870 7f0c8e54 00007fff 800a3b7c b74b8b80 000006b8 b775bf7c
[   37.521327] be80: 000000f7 b775bf50 b775a028 7f0c8fd0 b775bf48 7f0c8e90 809a9d4c 00000000
[   37.557055] bea0: 00000000 b74b8b80 00000000 00000000 00000000 00000000 00000000 00000000
[   37.593879] bec0: 00000000 00000000 00000000 00000000 6e72656b 00006c65 00000000 00000000
[   37.632092] bee0: 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
[   37.671741] bf00: 00000000 00000000 00000000 dc8cb005 b775bf2c 00000000 00000003 76fa8e80
[   37.711769] bf20: 0000017b 8000fd44 b775a000 00000000 b775bfa4 b775bf40 800a7b18 800a5530
[   37.752424] bf40: b775bf4c 8007fe70 bbd37000 00008dfc bbd3f71c bbd3c82b bbd3d960 00004000
[   37.793459] bf60: 00004310 7f0c8e00 00000003 00000000 0000002a 0000002b 00000023 0000001e
[   37.834493] bf80: 00000018 00000000 00000000 f7411c00 76fa4cdc 76f90f10 00000000 b775bfa8
[   37.875527] bfa0: 8000fac0 800a7a94 f7411c00 76fa4cdc 00000003 76fa8e80 00000000 00000002
[   37.916574] bfc0: f7411c00 76fa4cdc 76f90f10 0000017b 00000000 76fa4cdc 76fbb000 00000000
[   37.957609] bfe0: 7ec5abc0 7ec5abb0 76f9f6c3 76f0b812 80070030 00000003 3a7fa821 3a7fac21
[   37.998677] [<7f0cb064>] (rfm12_init_module [rfm12b]) from [<80008950>] (do_one_initcall+0xec/0x228)
[   38.040753] [<80008950>] (do_one_initcall) from [<800a70f0>] (load_module+0x1bcc/0x2430)
[   38.081918] [<800a70f0>] (load_module) from [<800a7b18>] (SyS_finit_module+0x90/0xc0)
[   38.122884] [<800a7b18>] (SyS_finit_module) from [<8000fac0>] (ret_fast_syscall+0x0/0x48)
[   38.164321] Code: e1a08000 e1a00004 eb4ac86d e2844001 (e7993108) 
[   38.187270] ---[ end trace 121fedc6486cd9e7 ]---

**Comment by klattimer** [comment]
Seems to be caused by this line 

u32* gpio = ioremap(0x20200000, SZ_16K);

which is unusual.

**Comment by klattimer** [comment]
Is only an issue on the Raspberry Pi B+ 2 

I guess the ioremap has changed

**Comment by klattimer** [comment]
I've added a pull request which resolves this issue in cases where the kernel headers aren't properly aligned with the particular board type.

**Comment by gkaindl** [comment]
The current master has support for the RPI2, so I'm closing this.
