### ISSUE TITLE
Any plans to add RFM69CW support? 

### ISSUE THREAD

**Issue by glynhudson** [gkaindl/rfm12b-linux#14]
Keep up the good work :+1:

**Comment by gkaindl** [comment]
yes, I'm already working on this in a feature branch: https://github.com/gkaindl/rfm12b-linux/tree/rfm69

right now, only receiving works, but I hope to have a fully compatible implementation done within a reasonable timeframe (currently, I'm quite busy with work, though).

I'm mostly excited about the 66-byte fifo – *finally* no more worries about interrupt latency!

**Comment by gkaindl** [comment]
@glynhudson just as a heads-up, I just merged the RFM69 support into master.

**Comment by glynhudson** [comment]
Good work!

**Comment by glynhudson** [comment]
Does two way transmission now also work? Can the RFM69CW receive communications from RF12B? Backwards compatible?

**Comment by gkaindl** [comment]
yes, that was actually my main intention! if you use the driver with rfm69 and rfm12, they are able to communicate with the default settings, e.g. no special configuration necessary. also, the driver auto-detects the radio module type when it is loaded, so you simply hook it up, load the driver and should be good to go.
