### ISSUE TITLE
request for clarification supporting kernel v3.18

### ISSUE THREAD

**Issue by jkarstest** [gkaindl/rfm12b-linux#15]
Hello gkaindl thank you for the nice module.
Can you figure out a little strategy do get this module running with 3.18 ?
I am not really familiar with kernel-modules, but with a little help and some hints might its possible to port this project to newer kernels.
My first suspect was that the reported problems only based by a deprecated installation instruction ?   

regards
Jens

**Comment by gkaindl** [comment]
I just updated the build instructions (also added support for the RFM69CW radio module) – I tested it on an RPI and RPI2 with recent kernel versions, and it should work.
