### ISSUE TITLE
[Raspbarry Pi 2 B] Error: could not insert module rfm12b.ko: Invalid module format 3.18.7-v7+

### ISSUE THREAD

**Issue by ChristianHH** [gkaindl/rfm12b-linux#16]
Hi, 
I tried to get this nice code to work. I followed the hints at the other issues, but I was not able to get this working. For a Linux-newbe like me, it was hard to get the code compiled, but now the last problem seems to be this:
   sudo insmod rfm12b.ko  delivers this error:

   Error: could not insert module rfm12b.ko: Invalid module format   

- Linux version 3.18.7-v7+ 
- /dev  rfm12b: disagrees about version of symbol module_layout

thanks for helping
Christian from Hamburg, germany

**Comment by realhuno** [comment]
I sucessfully using the the rfm12b-linux driver with my Raspberry Pi 2

the kernel drivers, read the comments:
http://l0l.org.uk/2015/02/headaches-whilst-upgrading-to-raspberry-pi-2/

read the last 2 comments:
http://l0l.org.uk/2013/11/rfm12b-linking-jeenode-micro-raspberry-pi/

sorry for my englisch, best regards from austria
huno

**Comment by ChristianHH** [comment]
Hallo,

vielen Dank für die Antwort - ich werde es probieren, komme wohl aber erst 
in 10 Tagen dazu.

Gruss aus Hamburg,

Christian

----- Original Message -----

**Comment by gkaindl** [comment]
I just merged in RFM69 support, which also addresses an incompatibility with the RPI2. I also updated the build instructions.

I've tested on an RPI2 now, and it works fine (for me).
