### ISSUE TITLE
insmod command hangs. Works on Raspberry 3?

### ISSUE THREAD

**Issue by marcolettieri** [gkaindl/rfm12b-linux#27]
I'm testing it on Raspberry 3 but the insmod command hangs...
this my kernel version: 4.4.14-v7+
The make works and outputs correctly the .ko but when i do "sudo insmod rfm12b.ko" no results are returned and i'm forced to stop it

**Comment by Phunkafizer** [comment]
Same problem on a Raspy 2B. Did you find a solution meanwhile?

**Comment by urbanpawel90** [comment]
+1

**Comment by marcolettieri** [comment]
Solved, you have to change platform and ricompile like older rasp versions

**Comment by urbanpawel90** [comment]
So I need to set Raspberry Pi instead of Raspberry Pi 2 in rfm12b_config.h file ?

**Comment by marcolettieri** [comment]
Raspberry pi 2 use the same gpio address of the raspberry 3 so you have to set for raspberry 2.

**Comment by Phunkafizer** [comment]
Found also my problem; pin configuration for CS pin was wrong
