### ISSUE TITLE
Network / Group ID?

### ISSUE THREAD

**Issue by felicitus** [gkaindl/rfm12b-linux#7]
The configuration says that I need to set a network/group ID. However, there's no indication of such an ID within the datasheet for neither the RFM12 nor the RFM12B. Is this a software-only feature?

If so, does it get disabled when not using the Jeelabs functionality?

**Comment by hecko** [comment]
This is documented in JeeLib documentation.

**Comment by felicitus** [comment]
As I was unable to get the information, I have ported the librfm12 from das-labor to Raspberry Pi and using it since. This can be closed.
